### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by topperge** [GeekyEggo/GoveeController#11]
This plugin is awesome, but I'd love to see support for it on the Mac as well. Not sure what I can do to help make that happen, but would be more than happy to support in some way.

**Comment by GeekyEggo** [comment]
Hey @topperge, thanks for the kind words; good news, the latest beta version comes with support for Mac. This isn’t on the Elgato store yet, but you can [download it from here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) directly.

**Comment by topperge** [comment]
Awesome, installed now. Now I just need to figure out how to chain commands together.
