### ISSUE TITLE
Capacity issue

### ISSUE THREAD

**Issue by Nob0dyExp3cts** [GeekyEggo/GoveeController#13]
Is there a limit to how many devices can be controlled in one multi action via the API

I use about 10 or so Govee devices and just installed another one. Now when I use my multiactions the last device in the command line doesn't change.

**Comment by GeekyEggo** [comment]
Hey @Nob0dyExp3cts, apologies for the _very_ late reply; Govee introduced API throttling earlier this year, which are likely causing issues in this scenario. Could I ask you to download the [latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) of the plugin that includes additional logging. After trying with this version, logs should be available at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`.

**Comment by GeekyEggo** [comment]
Closing to inactivity, please feel free to add a comment if required.
