### ISSUE TITLE
API Connects but device list is empty and refresh doesn't work. 

### ISSUE THREAD

**Issue by souzabg** [GeekyEggo/GoveeController#14]
![image](https://user-images.githubusercontent.com/44931685/182502874-ac06407b-52d6-45a1-9486-4d914bbed983.png)

**Comment by GeekyEggo** [comment]
Couple of things things to check;
1. Is the device model listed as supported in the [Govee API documentation](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf)?
2. If yes to the above, is the device connected to WiFi?

**Comment by souzabg** [comment]
> Couple of things things to check;
> 
> 1. Is the device model listed as supported in the [Govee API documentation](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf)?
> 2. If yes to the above, is the device connected to WiFi?

Hello sorry for the late response but my device is model H6147 which I could be wrong but I don’t think are supported even though they are WiFi. I also think that my lights are connected to WiFi as they work on the app to turn on through WiFi.

Thanks

**Comment by GeekyEggo** [comment]
Sadly if they aren’t supported by Govee’s public API, it won’t be possible to control them using the plug-in. Hopefully they add support soon!
