### ISSUE TITLE
problem with my device selection

### ISSUE THREAD

**Issue by Lukka05derechte** [GeekyEggo/GoveeController#15]
Hi I have a problem with my device selection because no device is displayed from my Govee devices.

https://user-images.githubusercontent.com/91662781/183612482-9212bc17-247a-45a6-8f83-3551a1199b5a.mp4

.

**Comment by GeekyEggo** [comment]
Hi Lukka, couple of questions,

1. What is the model of your device?
2. Is the device connected to WiFi?

**Comment by Xavier141524** [comment]
Hi having the same issue also. unable to select the devices...

Thanks!

**Comment by GeekyEggo** [comment]
Same questions apply, @Xavier141524.

**Comment by Xavier141524** [comment]
Sure my device is H6147 light strips and they are connected to wifi

**Comment by GeekyEggo** [comment]
> Sure. my device is H6147 light strips and they are connected to wifi

Sadly H6147 isn’t supported by the public [Govee API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf). As soon as they add support, it will automatically become available within the plug-in.

**Comment by Xavier141524** [comment]
That sounds good, thank you for the quick reply!

**Comment by Lukka05derechte** [comment]
Hi GeekyEggo I use the Govee H6159. The led stirp are not connected to the wifi. I control them with bluetooth. Can I also control the led strip with WiFi?

**Comment by GeekyEggo** [comment]
Hey Luca, thankfully the H6159 are supported by the Govee API; for them to work with the plugin, they will need to be connected to WiFi.

**Comment by Daarka** [comment]
I have this same issue. I am connected to wifi on the device, and its model is H5082. I also have two H5101 models that aren't showing up, either. If these aren't supported in the API, is there any workaround? :(

**Comment by GeekyEggo** [comment]
Hi @Daarka, sadly this is completely at the control of Govee. As new products are released, support is added for them. This can sometimes mean support for older models too. My recommendation would be to email them an express interest in API support for that model - the more people that do, will give them a better insight into where developer efforts should be focused.
