### ISSUE TITLE
Action not working

### ISSUE THREAD

**Issue by RomanXIV** [GeekyEggo/GoveeController#16]
I have the latest version of the plugin as well as the latest version of the app. However I still run into the issue where when I click on my stream deck it shows a green checkmark but nothing actually happens. The plugin does recognize my Govee and I have product model H6062 which is compatible, but I still can't get the action to actually be applied. Any suggestions?

**Comment by GeekyEggo** [comment]
Hey @RomanXIV, so I can look into this further, could you please upload the log files, they can be found at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`.

**Comment by RomanXIV** [comment]
Hey @GeekyEggo I tried to find the logs but when I went into com.geekyeggo.goveecontroller.sdPlugin there were no logs it showed a folder for images and a folder for pi. Then a bunch of files below.  I requested a new API and tried again but nothing changed as of yet. what should I try next?

**Comment by GeekyEggo** [comment]
I’d recommend trying the latest [beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin); there are a lot of fixes within here that might solve your issue. Download and try with this version, and if that doesn’t work, check to see if any log files were generated and we’ll go from there.

**Comment by oooJYNXooo** [comment]
Hi! I just got the streamdeck and noticed that the moment I set up multiple commands on many ligths, that it will show a yellow EXCLAMATION sign and not execute the commands.  I also looked in the logs as you suggested to the other user and see nothing. How would I go about installing this beta version?  many thanks!

**Comment by oooJYNXooo** [comment]
never mind on how to install... figured it out. Had to first uninstall. Same problem however!

**Comment by GeekyEggo** [comment]
Hey @oooJYNXooo, could you raise a new ticket detailing the problem you’re having please. I’ll look into it.

**Comment by GeekyEggo** [comment]
Consolidating all generic failures into #20, which resolves some HTTP errors.
