### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by andrew-mitchell-721** [GeekyEggo/GoveeController#17]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

macOS

### Govee Device

Multiple - haven't gotten to the point of needing to add them yet, so this isn't the issue.

### Bug Description

When trying to download via [this page](https://apps.elgato.com/plugins/com.geekyeggo.goveecontroller), I get the following error:

```
The plugin “com.geekyeggo.goveecontroller” is not available for download.
```

When downloading directly via the [release page](https://github.com/GeekyEggo/GoveeController/releases/tag/v1.0.0), I get the following error when running the downloaded plugin file:

```
“com.geekyeggo.goveecontroller” can't be installed on this machine.
This custom action can't be installed on this operating system.
```

Running MacOS 12.5 on a Mac Studio (M1 Max). Did I miss something about an M1 compatibility issue?

### Logs

```bash
N/A
```

**Comment by GeekyEggo** [comment]
Hey @andrew-mitchell-721, could I ask you to try the [latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin); hopefully this should solve the problem. 🤞

**Comment by andrew-mitchell-721** [comment]
That worked perfectly! Thanks for the quick response!
