### ISSUE TITLE
Too many actions at once stops further actions until some time passes

### ISSUE THREAD

**Issue by oooJYNXooo** [GeekyEggo/GoveeController#18]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

Givee Lights and switches
H6008
H5080

### Bug Description

I've setup a multi action shortcut in the streamdeck to do many things.
It seems that after turning on 3 lights, changing the same 3 lights to a different color, adjusting 3 lights brightness AND then trying to do something else, I may get away with perhaps 1 or maybe 2 more Govee interactions but then it stops working and I see a yellow sign with an exclamation mark appear on the streamdeck.
I've looked for any logs but I can not find them on my system under the plugins sub folder

**Comment by GeekyEggo** [comment]
Hey @oooJYNXooo, thanks for the providing a good amount of information as to what's happening; Govee recently implemented API throttling, which I suspect may be the case here. To confirm, could I ask you to download the [latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) of the plugin. This version includes additional logging that will enable us to determine what's going on. After trying with this version, logs should be available at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`.

**Comment by oooJYNXooo** [comment]
Response: TooManyRequests Rate limit exceeded, retry in 53 seconds.

Response: TooManyRequests Rate limit exceeded, retry in 54 seconds.

Rate limit exceeded, retry in 54 seconds.

**Comment by oooJYNXooo** [comment]
This really sucks. I had set up a whole bunch of combinations to change lights on the fly while gaming, and it always stops when I most need it!  
Is there any way to by pass this?

**Comment by GeekyEggo** [comment]
> Is there any way to by pass this?

Sadly not, but you might be able to adjust your setup and reduce the number of calls to be within the thresholds defined in the [Govee API specification](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf). In an ideal world there would be better support for “scenes” to reduce the number of requests; I’m sorry I couldn’t be of more help.
