### ISSUE TITLE
Lan control?

### ISSUE THREAD

**Issue by chaixshot** [GeekyEggo/GoveeController#19]
### Pre-Checks

- [x] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

All

### Bug Description

New govee firmware update has lan control enable for all device.
Can you update this script for support that?

**Comment by GeekyEggo** [comment]
Hey @chaixshot, checking the [Govee API docs](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf), it seems the devices still require WiFi to be controlled via the API.

**Comment by GeekyEggo** [comment]
Hey @chaixshot, thanks for bringing my attention to this, I wasn't aware Govee had added support for appliances. I would love to add this functionality, but at the moment I don't have any devices to test this with. Should this change, I will release an update with the added features. 👍
