### ISSUE TITLE
setup failed: sucess

### ISSUE THREAD

**Issue by Joshkmillr** [GeekyEggo/GoveeController#2]
![image](https://user-images.githubusercontent.com/98286253/150698346-11a82007-f82c-4cfc-8f50-ec6c7244440c.png)

Received the API Key from Govee and after entering it into the Stream Deck and connecting, a "setup failed: success" message appears.

**Comment by GeekyEggo** [comment]
Haha, oh dear, that's an interesting one. Could I ask you to:
1. Download and install the latest beta version of the plugin from [here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).
2. With the beta version, try connecting to Govee again.
3. Upload the logs from `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`

**Comment by Joshkmillr** [comment]
> 
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/7922752/GoveeController.log)

**Comment by Joshkmillr** [comment]
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/7928671/GoveeController.log)

Still no luck. I believe it has to do with Wi-Fi. For background, my apartments Wi-Fi is a bit weird (its a student apartment) . Each connected device that has its own MAC address has its own password. So devices such as google home/Alexa etc. that are connected to Wi-Fi through an app are not able to be connected. At least I have not found a way to go around it, cant even add my own router. So looks like I have to use Bluetooth, will look into it more on my side

**Comment by GeekyEggo** [comment]
Thanks for the update Josh; as the Govee API relies pretty heavily on WiFi, I would definitely speculate the current setup being troublesome. I'm not sure if it would work, but you could try tethering your devices to your phone via a hotspot?

**Comment by GeekyEggo** [comment]
As I'm not able to assist any further I'm going to close this @Joshkmillr; if you are eventually able to connect the devices to WiFi, and continue to encounter problems with the plug-in, please let me know I can re-open this issue.
