### ISSUE TITLE
Plugin Missing for M1 Macs

### ISSUE THREAD

**Issue by Stoyvo** [GeekyEggo/GoveeController#21]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

macOS

### Govee Device

H6062

### Bug Description

In Stream Deck Plugins, on Windows 11 this plugin is available, however M1 Macs do not have this plugin available.

Works flawlessly with Windows 11, thank you! I do not know requirements for M1 mac support, but I'm happy to provide a build if that's the need.

**Comment by GeekyEggo** [comment]
Hey @Stoyvo, could you try with the latest beta, v1.2.2; you can download it from [here](https://github.com/GeekyEggo/GoveeController/raw/fix-http/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

**Comment by Stoyvo** [comment]
@GeekyEggo How do I install it?

**Comment by Stoyvo** [comment]
Oh... you just double click. Sorry for the noob question.

**Comment by Stoyvo** [comment]
@GeekyEggo It appears to work, however it appears to be intermittent. This may be due to multi-actions and API rate limits? Haven't seen the issue on Windows 11 though.

**Comment by GeekyEggo** [comment]
The intermittency could be the result of the API, which can prove temperamental at times, particularly when using multi-actions. If you continue to experience problems, I'll be happy to take a look at them in a new ticket.
