### ISSUE TITLE
Won't install on Streamdeck

### ISSUE THREAD

**Issue by dartiss** [GeekyEggo/GoveeController#23]
I'm getting this error when trying to install the plugin...

<img width="578" alt="Screenshot 2022-10-21 at 14 51 24" src="https://user-images.githubusercontent.com/14928971/197212166-1aec5b2b-1c5c-4e23-ad08-3c579b8795ff.png">

This is on a MacBook Pro M1 Pro, MacOS 12.6

**Comment by GeekyEggo** [comment]
Hey @dartiss, is this via the Stream Deck store, or the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin)?

**Comment by dartiss** [comment]
It was from Github but wasn't the beta... just tried that and it's worked. 

It's not in the Stream Deck store, is it (I can't find it)?

**Comment by GeekyEggo** [comment]
> It's not in the Stream Deck store, is it (I can't find it)?

The macOS one is currently marked as beta as I haven't been able to test it myself; it has been tested by other members of the community however, so should work fine.
