### ISSUE TITLE
API code not staying connected

### ISSUE THREAD

**Issue by madmonkeyfun** [GeekyEggo/GoveeController#24]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

Govee glide wall lights

### Bug Description

When I enter my API key into the app it works for the day, as soon as I turn off my PC and fire it up the next day the plugin does not work, I have to manually uninstall the plugin and set it up as though it was new. 
Any suggestions or fixes for this?
It's a great app and I love being able to use it with my stream deck. but at the moment I can't as it's frustrating to use.

**Comment by GeekyEggo** [comment]
Hey @madmonkeyfun, could I ask you to try with the latest beta version ([download](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin)); this includes a lot of fixes that will hopefully resolve the issue.

**Comment by madmonkeyfun** [comment]
Ok, Thank you, I'll give it try over the next couple of days and let you know how I get on

**Comment by biglat1595** [comment]
I have the same problem. I can try also tomorrow with the beta version.

**Comment by biglat1595** [comment]
Hey @GeekyEggo tests are OK for me. After restart my computer, plugin continues to work.

**Comment by madmonkeyfun** [comment]
Good Morning, Sorry for not replying earlier, I can confirm that the Beta version worked for me, thank you for that, Do you have any plans to add the choice for adding scenes to the software, we can already select colours but on the Govee app you can add a scene that move, not sure if it's something you have planned or not.

**Comment by GeekyEggo** [comment]
Great to hear the latest beta has resolved the problem!

@madmonkeyfun, regarding scenes; sadly this aren't yet supported by the public Govee API. Should that functionality become available, I'll do what I can to add support in the plugin.
