### ISSUE TITLE
Stream Deck recognizing H6159, but not changing anything

### ISSUE THREAD

**Issue by GGB195** [GeekyEggo/GoveeController#25]
My stream deck has stopped controlling my strip lights. I have requested a new API from Govee, as well as uninstalled the Govee Controller from the stream deck and reinstalled it. The stream deck is finding the strip lights, as well as giving the green check mark, but nothing is changing. I have full control of the strip lights from the app. Just not able to control them from the stream deck.
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/9985110/GoveeController.log)

**Comment by GeekyEggo** [comment]
Hey @GGB195, I’ve had a look at the logs, but nothing is jumping out at me. Could I ask you to try with the latest beta ([download link](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin)).

**Comment by GGB195** [comment]
@GeekyEggo After downloading the latest beta, I still was having the same problems. I ended up turning my phone off, no change. I checked to see if the iPhone app needed to be updated, it was up to date. I re-entered the wifi settings info, now it is working. The joys of tech. Thanks for the responsiveness!

**Comment by GeekyEggo** [comment]
I had a similar issue with the WiFi on my lightstrip; it said it was connected, but definitely wasn’t. It required a factory reset to fix it. 🙈 

Glad to hear the problem is resolved.
