### ISSUE TITLE
Setup Failed when entering API key

### ISSUE THREAD

**Issue by Psykrot** [GeekyEggo/GoveeController#26]
I get the message: "Setup failed: rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time." when entering the API key into the field on the Stream Deck app and clicking Connect

This is a brand new API Key that was applied for about 5 minutes before I input it.

Please let me know if there is something that I am doing wrong

**Comment by GeekyEggo** [comment]
Hey @Psykrot, could I ask you to try with the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin); it includes a lot of fixes, particularly around entering an API key.

If the problem persists with the beta, if you upload the logs, I’ll take a look. They are located at;
`%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`

**Comment by Psykrot** [comment]
Yes! it working flawlessly now. Love that I can use a color picker since IFTTT only has pre-chosen colors

**Comment by GeekyEggo** [comment]
That's fantastic news! 🥳
