### ISSUE TITLE
Setup failed: Invalid API Key

### ISSUE THREAD

**Issue by sparkyga** [GeekyEggo/GoveeController#27]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Setup failed: Invalid API Key###

**Device: **RGBIC Led Strips
**Product Model: **H617E

### Bug Description

Getting an error when putting in a valid API key

I am currently using the beta version, since the previous person who reported this problem said this fixed their issue, it has not fixed mine

### Logs

```bash
I can't find it
```

**Comment by GeekyEggo** [comment]
Hey @sparkyga, in Stream Deck, can you right-click one of the actions in the right hand side to view the version of the plugin, it should say 1.2.2, like so:
![image](https://user-images.githubusercontent.com/1429781/203597867-db8fdb1d-f27f-4862-8bb1-128cf403d74f.png)

As you're running on Windows, the logs should hopefully be located at:
`%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\win\logs`

**Comment by sparkyga** [comment]
Okay I found the logs:
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/10087000/GoveeController.log)

I also can confirm that it is 1.2.2

What's next?

-Sparkyga

**Comment by GeekyEggo** [comment]
Thanks @sparkyga.

I’ve had a look at the logs, and there’s good news and bad news. The good news is the API key is okay. Sadly however, after looking at [Govee’s documentation](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf), the H617E isn’t listed as supported by their public API. This means the plug-in won’t be able to control the light-strip.

I’m sorry I couldn’t help you more.

**Comment by sparkyga** [comment]
Oh, thats unfortunate... hopefully Govee adds support for these in the future, thanks for helping.
