### ISSUE TITLE
No funciona la opcion

### ISSUE THREAD

**Issue by pabloramiirezz** [GeekyEggo/GoveeController#29]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

las luces son
H613B

### Bug Description

al principio me daba error y no podía ponerla ip me metí aquí y vi que le ayudaste a unos cuantos con la ip y descargue la versión que pusiste y ahora parece que se ha conectado la ip y todo pero cuando le doy al botón me sale el triangulito este y no hace nada le puse el atajo de apagarse y me salió el triangulo y no se apago

![image](https://user-images.githubusercontent.com/119074876/204042080-c9c5801d-71ea-4aaa-9d5f-0760e554e3cd.png)

[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/10094716/GoveeController.log)

### Logs

```bash
no me deja pegarlo
esta arriba
```

**Comment by GeekyEggo** [comment]
Hi @pabloramiirezz, desafortunadamente, Govee’s API no es compatible con ese dispositivo.

**Comment by pabloramiirezz** [comment]
y no puedes hacer q sea compatible?

**Comment by GeekyEggo** [comment]
No puedo lo siento. Solo Govee puede agregar soporte.
