### ISSUE TITLE
Govee keeps not working

### ISSUE THREAD

**Issue by itzerik** [GeekyEggo/GoveeController#30]
Govee keeps not being able to work after a while it gives me the triangle error

**Comment by dcsublime** [comment]
I too am having trouble with a constant triangle error.  Let me provide more details that might help.  On an existing button or a new added button for the GoveeController, I go to edit and under device there is nothing to choose from.  Then I found this and downloaded and installed the latest beta from the link.  After installing I then under the device option, get a constant loading message with a refresh button, but nothing loads.  After closing the stream deck application and opening again, the device option is once again blank.  I appreciate your work on this application and hope this helps to improve this issue.  If you need anything I am here to help.  Thank you.

**Comment by GeekyEggo** [comment]
Hey @dcsublime, I'm sorry to hear you're encountering problems; to help determine if this is related:
- What devices are you attempting to control?
- Is the device model listed as supported by the [Govee public API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf) (page 2)?
- Is the device connected to WiFi?

**Comment by dcsublime** [comment]
> 

Hello and thank you for the response.  I did forget to mention that all these devices worked until recently.  

-  I am using several different devices plugs, light strips, and flow bars.  One example that I use many of and often is the H5081.
- The H5081 is listed as supported on the page mentioned.
- The devices are connected to Wifi and and I am able to control them with the Govee app.

On a button when I when I mouse over the device "which is now empty", I this message. (I am transposing, so forgive me for an error)  "rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time"

**Comment by GeekyEggo** [comment]
Are the actions part of a multi-action? Govee enforces strict throttling on API calls, although it _shouldn’t_ be exceeded, there’s a chance it can.

**Comment by dcsublime** [comment]
No sir these are all simple toggle on/off buttons and one button for each device.

**Comment by GeekyEggo** [comment]
> No sir these are all simple toggle on/off buttons and one button for each device.

If you're happy to, could you upload your log file to this ticket; the logs will hopefully provide more insight into what is happening under the hood. The file can be found here:
`%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\win\logs`

**Comment by GeekyEggo** [comment]
I’m going to close this ticket due to inactivity, but I’ll be happy to review the logs should you wish for the investigation to continue. 😄

**Comment by DrewMcNeill** [comment]
Apologies for jumping on this thread @GeekyEggo, but i'm currently experiencing the same error here.
I've had a look on the log file, and getting the message "Device identifier cannot be null. (Parameter 'deviceId')"

Could you advise please?

**Comment by GeekyEggo** [comment]
Hey @DrewMcNeill, could I ask you to try the [latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin); this has a lot of fixes and should hopefully resolve the issue. 🤞

**Comment by DrewMcNeill** [comment]
Hi Richard,
Thanks for the reply and the beta version download.
This is currently the version I have installed.
I seem to be getting a Green Warning Triangle appear when toggling on/off.
(Setup Govee API key etc correctly)

Let me know if I can give anymore supporting info.
Thanks.



On 6 Feb 2023, at 23:17, Richard Herman ***@***.***> wrote:



Hey @DrewMcNeill<https://github.com/DrewMcNeill>, could I ask you to try the latest beta version<https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin>; this has a lot of fixes and should hopefully resolve the issue. 🤞

**Comment by GeekyEggo** [comment]
No problems; when you next have the opportunity to, could you please:
1. Replicate the error, and then upload your log files here.
2. Re-create a new action (on a different button), to ensure the settings haven’t become corrupt.

**Comment by DrewMcNeill** [comment]
This is the error log I’m getting (I think - correct me if this isn’t the right log, I’ve not used Console much)

10:23:21.9366 Device identifier cannot be null. (Parameter 'deviceId')
10:23:22.5941 Device identifier cannot be null. (Parameter 'deviceId')

I’ve uninstalled / reinstalled and entered the API key again from scratch.

Thanks,


On 6 Feb 2023, at 23:23, Richard Herman ***@***.***> wrote:



No problems; when you next have the opportunity to, could you please:

  1.  Replicate the error, and then upload your log files here.
  2.  Re-create a new action (on a different button), to ensure the settings haven’t become corrupt.

**Comment by GeekyEggo** [comment]
Thanks Drew; as no sensitive information is contained within the log file, could you upload the entire file to this ticket please. Also, would it be possible to get a screenshot of your settings window in Stream Deck for the action that is causing the issue.

**Comment by DrewMcNeill** [comment]
Sure no problem.
Let me know if you need anything else.

Thanks,

***@***.***


On 7 Feb 2023, at 12:35, Richard Herman ***@***.***> wrote:



Thanks Drew; as no sensitive information is contained within the log file, could you upload the entire file to this ticket please. Also, would it be possible to get a screenshot of your settings window in Stream Deck for the action that is causing the issue.
