### ISSUE TITLE
Not available to download

### ISSUE THREAD

**Issue by emanuelstanciu** [GeekyEggo/GoveeController#31]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

macOS

### Govee Device

Govee Flow Pro

### Bug Description

Govee Controller is not available to download in the Elgato Stream Deck plugin store.

**Comment by GeekyEggo** [comment]
Hey @emanuelstanciu, macOS is currently supported as part of the beta; here is a [direct download link](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin). If you have any problems, please let me know, and thank you for supporting it's development! 💖

**Comment by GeekyEggo** [comment]
@emanuelstanciu I'm going to close this ticket, but if you have any issues, please don't hesitate to ask.

**Comment by emanuelstanciu** [comment]
thanks Richard
