### ISSUE TITLE
GoVee Smart Plug Support

### ISSUE THREAD

**Issue by AEBog** [GeekyEggo/GoveeController#32]
I just picked up a few GoVee smart plugs. I would expect them to work just like a light in the On-Off action if they can be easily added to the list. What do you think?

**Comment by GeekyEggo** [comment]
Hey @AEBog, do you have the model number for the device?

**Comment by AEBog** [comment]
H5083

**Comment by GeekyEggo** [comment]
Hey @AEBog, sadly the H5083 isn't supported by [Govee's public API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf) (page 2). Without support from Govee, it won't be possible to control these devices with Govee Controller.

**Comment by AEBog** [comment]
Thanks for checking!

**Comment by AEBog** [comment]
The H5080 and H5081 smart plugs are listed as supported by the API. I'll return the H5083 and try a H5080.
