### ISSUE TITLE
QUESTION NOT ISSUE: Is there anyway to turn off multiple devices with one button on my stream deck or will I need multiple inputs to turn off each Govee product I have?

### ISSUE THREAD

**Issue by mikey5469** [GeekyEggo/GoveeController#33]

**Comment by GeekyEggo** [comment]
Hey @mikey5469, did you to achieve what you wanted to do? A recommended approach is to setup a “Multi Action”, and then add an action per device. This will allow you to press a single button, and control multiple devices.
