### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by Foxworth22** [GeekyEggo/GoveeController#34]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

macOS

### Govee Device

N/A

### Bug Description

Does not yet support running Elgato Stream Deck from macOS environment

**Comment by GeekyEggo** [comment]
Hey @Foxworth22, good news - macOS is supported as part of the latest beta! Although it isn’t yet on the store, it can be [downloaded directly from here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

**Comment by Foxworth22** [comment]
I noticed that was two months ago. Is the beta public now?

**Comment by GeekyEggo** [comment]
That's correct, currently macOS is only supported as part of the public beta, which can be [downloaded directly from here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

**Comment by Foxworth22** [comment]
Sorry, I meant is it out of beta yet?

**Comment by GeekyEggo** [comment]
Apologies for the misunderstanding; it isn't yet out of beta. I'm apprehensive to push to live as I'm unable to fully test on macOS without the hardware. There are no active changes happening as part of the beta, and it should be considered stable, i.e. the current version _would_ become the live release.
