### ISSUE TITLE
Refuses to install on Streamdeck MacOS app

### ISSUE THREAD

**Issue by jbowdach** [GeekyEggo/GoveeController#35]
![CleanShot 2023-01-06 at 15 09 19](https://user-images.githubusercontent.com/227542/211114813-4ff6c808-5f2c-4292-92a4-c4b7195c6aa2.png)

Provides the attached error when either downloading from the Elgato site or Github. Running MacOS Ventura and running Streamdeck SOftware 6.0.2

**Comment by GeekyEggo** [comment]
Hey @jbowdach, macOS support has recently been added as part of the latest beta. This isn’t yet available on the store, but can be [downloaded directly from here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin). Hope this helps! 😄

**Comment by jbowdach** [comment]
> Hey @jbowdach, macOS support has recently been added as part of the latest beta. This isn’t yet available on the store, but can be [downloaded directly from here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin). Hope this helps! 😄

Thank you so much! Working perfectly now :)
