### ISSUE TITLE
Feature Request: Select list of lights to toggle

### ISSUE THREAD

**Issue by joeygallegos** [GeekyEggo/GoveeController#38]
**Reason:** Right now, we can only take action (like toggle on/off) on one light per Stream Deck button press.

**Request:** Make it so that you can group lights and toggle all of them on/off at the same time.

**Comment by GeekyEggo** [comment]
Hey @joeygallegos 👋 the best approach to achieving this currently is through a “Multi action” within Stream Deck. Sadly, the Govee API doesn’t provide access to scenes right now, but rest assured, as soon as that changes, I’ll add support! 😄
