### ISSUE TITLE
Toggle Scenes

### ISSUE THREAD

**Issue by expertrogers** [GeekyEggo/GoveeController#39]
This isn't an issue, it's a suggestion, it would be great if we could toggle build in or custom scenes on the stream deck. I have the H6056 LED bars and I love changing what scene they are running on which I can only do with the app on my phone but using the deck would be quicker and more convenient.

**Comment by joeygallegos** [comment]
@expertrogers I just purchased the H6056 model. Did you hit up the Amazon sale? Lol
I totally agree with this proposal. I just opened a feature request, too.

**Comment by expertrogers** [comment]
I got them in august for my birthday, they are so much better then I was expecting. Lol

**Comment by GeekyEggo** [comment]
Hey @expertrogers I would absolutely _love_ to add an action for scenes; sadly, at the moment, Govee’s public API doesn’t provide access to scenes, so this isn’t possible. Should this change in the future, I will certainly add it to the plug-in! 😄
