### ISSUE TITLE
1.Stream Deck App not working with Govee light strip. 2. how to use "scene" from Govee app on stream deck.

### ISSUE THREAD

**Issue by Spartan461** [GeekyEggo/GoveeController#4]
## Pre-checks

- [x] The device is connected via WiFi.
- [x] The device is supported by the public API. ([list of supported devices](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf)).

## Description
- Describe the bug; a clear and concise description of what the bug is.
- Include the affected product's model number.

## Logs and Screenshots

- Please attach logs from `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`.
- If applicable, add screenshots to help explain the problem.

**Comment by GeekyEggo** [comment]
Closing this as it’s gone quiet; happy to re-open if the problem persists.
