### ISSUE TITLE
Request: Scene Toggles

### ISSUE THREAD

**Issue by Murphy1976** [GeekyEggo/GoveeController#41]
I have a strip of Govee LED lights that I have connected to my Elgato Stream Deck XL, and I'm wondering if there are any plans to expand the functionality of the Govee Controller so we can switch between premade scenes or custom scenes we have created with the Govee Home app?

**Comment by GeekyEggo** [comment]
Hey @Murphy1976 👋 Having the ability to control scenes is something I’d love to add, but sadly as it stands this functionality isn’t supported by Govee’s public API. Should this change in the future, I will do what I can to bring it to the plug-in!
