### ISSUE TITLE
No response to action on Stream deck MK2

### ISSUE THREAD

**Issue by JCAB4534574** [GeekyEggo/GoveeController#44]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

Govee RGBIC Light stip 10M
Govee Glide light bars 

### Bug Description

When clicking the on/off button On my streamdeck MK.2 nothing happens and the same happens with the brightness section of the plugin, I have already connected the API Correctly and assigned it a device and action! could you help me?

**Comment by GeekyEggo** [comment]
Hey @JCAB4534574 without the log files and device identifiers, I'm afraid I won't be able to investigate the route cause or provide an accurate solution. In the interim, I would recommend testing with the [latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin). This incorporates a lot of fixes that may resolve the issue.

**Comment by JCAB4534574** [comment]
Hi thanks for the reply, whilst messing around it appeared that my govee products needed updating and connecting to my newly installed Wi-Fi network, All is running perfectly now and it is so helpful, thanks for your service! :)
