### ISSUE TITLE
"Setup failed: service is busy please try again later"

### ISSUE THREAD

**Issue by icantpronouncethis** [GeekyEggo/GoveeController#47]
When I try using the Govee Controller Button
this pops up.
"Setup failed: service is busy please try again later"
it seems like a maintenance thing.
I was wondering if there is a solution for this.

Thank you

**Comment by xCaptainCanadax** [comment]
Seems to be working as of this post, weird issue maybe on Govee end.

**Comment by icantpronouncethis** [comment]
it works now. i guess it was on Govee's end as the cap said

**Comment by GeekyEggo** [comment]
Glad to hear this has resolved itself. It definitely sounds like an intermittent maintenance thing; this is the first time it’s been reported, so hopefully it’s infrequent. 🤞
