### ISSUE TITLE
New features IDEA: Bluetooth Control

### ISSUE THREAD

**Issue by nayzflux** [GeekyEggo/GoveeController#48]
I have an idea to **allow the control** to  **Govee Light Strip** that are **only Bluetooth** and **not supported** by **Govee API**.
Like the H6125.
Users could **choose** between using **Govee API** or Bluetooth to control their lights.
I think its a good idea because **only-Bluetooth lights strip cannot be controlled** by Stream deck and it will **support all unsuported light strips**.
I have seen that is possible to use Bluetooth here:
- https://github.com/ib0b/RGB-PC
- https://github.com/andydam/lights

**Comment by Undivided-1** [comment]
Why no Mac support?

**Comment by GeekyEggo** [comment]
@Undivided-1, macOS is supported in the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

**Comment by Undivided-1** [comment]
> @Undivided-1, macOS is supported in the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

THANK YOU so very much :)

**Comment by Undivided-1** [comment]
Once I have my API and add it to the Govee Controller in Streamdeck, do I do anything else?  Just says connecting and that's it.

**Comment by GeekyEggo** [comment]
@Undivided-1 if you’re experiencing problems, could I please ask you raise a separate ticket, and we can look into it there.

**Comment by Ravin-Haven** [comment]
Stream deck + Dial support? Would be fantastic if this could be a possibility!

**Comment by GeekyEggo** [comment]
With Govee's new API, and enhanced functionality capabilities, I'm going to close this as out of scope. With the release of v1.3 now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), the plugin has been updated to use Govee's new API, and will see future improvements and extra functionality added over time.
