### ISSUE TITLE
Hello, I need help connecting my govee lights to my stream deck

### ISSUE THREAD

**Issue by Xenphu** [GeekyEggo/GoveeController#5]
## Pre-checks

- [x] The device is connected via WiFi.
- [x] The device is supported by the public API. ([list of supported devices](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf)).

## Description
- Describe the bug; a clear and concise description of what the bug is.
- Include the affected product's model number.

## Logs and Screenshots

- Please attach logs from `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`.
- If applicable, add screenshots to help explain the problem.

**Comment by Xenphu** [comment]
Hello, I connected my govee lights to my stream deck however, the functions are not working.

**Comment by GeekyEggo** [comment]
Hi @Xenphu, could I ask you to try with the latest [beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin), and if the problem still persists upload the logs found at `%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs `

**Comment by Xenphu** [comment]
i dowloaded the latest beta version

**Comment by Xenphu** [comment]
how do i do the upload logs?

**Comment by Xenphu** [comment]
or what do i do after i download it?

**Comment by GeekyEggo** [comment]
After downloading the beta, if you double-click it it will install the latest version. Hopefully this will solve the problem.

**Comment by Xenphu** [comment]
i downloaded it but, it still doesn't work

**Comment by Xenphu** [comment]
how do i do upload logs?

**Comment by GeekyEggo** [comment]
You should be able to drag/drop the upload file here.

**Comment by GeekyEggo** [comment]
Hi @Xenphu I'm closing this, but if you continue to have problems please let me know and we can discuss things here.
