### ISSUE TITLE
Control All Lights at Once?

### ISSUE THREAD

**Issue by TheJerilla** [GeekyEggo/GoveeController#50]
Is there a function to control all of my Govee lights at once? Right now it's only letting me select each light individually, but I have four lights and I don't want to push four buttons.

**Comment by GeekyEggo** [comment]
Hey @TheJerilla, thankfully this functionality is built into the Stream Deck; the “Multi-action” action will allow you to control all of your lights. 🙌

**Comment by TheJerilla** [comment]
Oh thank you so much for that info! Sorry, I'm new to the Stream Deck haha. Thanks for your time. :)

**Comment by GeekyEggo** [comment]
No problems at all; let me know if you encounter any issues, I’ll be happy to help. 😄
