### ISSUE TITLE
Unable to use my Govee API

### ISSUE THREAD

**Issue by Undivided-1** [GeekyEggo/GoveeController#51]
I am using an M2 Mac mini
I have my Govee API and I have installed the beta plugin into my Stream deck
I am trying to make an ON/OFF toggle and I am putting in my API
Streamdeck just says connecting and nothing happens.
I have gone over to my Govee Developer portal and I am able to test my API
I can list my devices, get my device status state and also control my device
I would guess that my API is working just not with streamdeck?.

The controller is not asking for my devices MAC address or model.  Just the API

I must be doing something wrong or have not completed a step.

Anyone have any ideas?

**Comment by Undivided-1** [comment]
After some troubleshooting I believe I know what is going on.  Govee uses the 2.4 band and my Mac is automatically choosing the 5ghz band.  My Optimum router has the same SSID for the different bands and I do not see a way to separate them.  I tried a few ways to force my Mac to use a specific channel but this does not work.

**Comment by Undivided-1** [comment]
Anyone??

**Comment by GeekyEggo** [comment]
Hey @Undivided-1, so I’m able to investigate this further, could I please ask you to upload the logs file to this issue. This can be found at:
```
~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.geekyeggo.goveecontroller.sdPlugin
```
And then in the macOS folder, there should be a “logs” folder.

**Comment by Undivided-1** [comment]
I do not see a logs folder in the com.geekyeggo.goveecontroller.sdPlugin folder
I see an osx folder but there is no log folder there either

**Comment by GeekyEggo** [comment]
If you navigate to `~/Library/Logs/StreamDeck/`, are there any folders there that resemble `com.geekyeggo.goveecontroller`?

**Comment by GeekyEggo** [comment]
Hmm, sadly it sounds as though the plugin isn't running. 🤔 Could I ask you to:
1. Uninstall the plugin (right click one of the actions, and then "Uninstall").
2. Restart your laptop.
3. Download and install the [latest beta](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

**Comment by Undivided-1** [comment]
I uninstalled the plugin and restarted my Mac mini
I downloaded and installed the latest Beta
When I add my API to the controller, it just says Connecting and nothing happens
I navigated to ~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.geekyeggo.goveecontroller.sdPlugin/OSX and still do not see any logs folder
Could this be an issue with the M2 Mac?

**Comment by Undivided-1** [comment]
So in the JSON file, I see the Code path for the Mac controller - 
~/Library/Application Support/com.elgato.StreamDeck/Plugins/com.geekyeggo.goveecontroller.sdPlugin/OSX/GoveeCOntreoller 

If I run this I get an error saying Zsh: bad CPU

**Comment by GeekyEggo** [comment]
Hey @Undivided-1, just catching up on tickets - great to hear everything is now working! I’m going to close this ticket, but if you have any further questions or problems, please don’t hesitate to ask.
