### ISSUE TITLE
Feature Request: Use scenes like "rainbow" for RGBIC

### ISSUE THREAD

**Issue by miriambrueckner** [GeekyEggo/GoveeController#53]
Hi there! Thanks for the awesome plugin! I got my first govee lights today and could connect it without any problems. The only thing that I am missing is some more flexibility for RGBIC lights. In the govee app there are scenes like "rainbow" which I would really like to be able to use via my Stream Deck :)

**Comment by GeekyEggo** [comment]
Hey @miriambrueckner 👋 Happy to hear you’re all and running, and everything is working. At the moment, Govee’s public API doesn’t allow for changing scenes from third-party apps, so this functionality isn’t possible as part of the plug-in. Should this change in the future, I’ll be sure to add the functionality. 🤞

**Comment by miriambrueckner** [comment]
Maybe I got something wrong, but scenes are part of the official govee app,
aren't they?

Am Fr., 14. Juli 2023 um 15:53 Uhr schrieb Richard Herman <
***@***.***>:

**Comment by GeekyEggo** [comment]
That's correct, Scenes are available in the official app. Sadly the app and public APIs are different, which means functionality for third-party developers is reduced - one of these areas specifically is Scenes which means these can't be read/changed/set outside of the official app.

**Comment by miriambrueckner** [comment]
Thanks for clarifying!

Richard Herman ***@***.***> schrieb am Sa. 15. Juli 2023 um
13:14:
