### ISSUE TITLE
Feature Idea:  Appliance Support

### ISSUE THREAD

**Issue by jpalarchio** [GeekyEggo/GoveeController#54]
Any consideration for adding support for the "appliance" category of devices in the API?

Specifically looking to be able to turn a H7130 space heater on and off without depending on IFTTT.

**Comment by GeekyEggo** [comment]
Hey @jpalarchio, I'd love to add appliance support, however at the moment I don't have an appliance to test with.

I'm going to flag this as "help-wanted", in the hope that someone with an appliance wishes to add such functionality 😄

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
