### ISSUE TITLE
GoveeController for Stream Deck on Mac

### ISSUE THREAD

**Issue by discolemonade01** [GeekyEggo/GoveeController#55]
Can someone please create a Govee Controller for Stream Deck for the Mac? I have an Elgato Stream Deck and a Govee light. Thanks.

**Comment by GeekyEggo** [comment]
Hey @discolemonade01, good news, macOS is supported as part of the [latest stable beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin). You should be able to download it, double click it, and have Stream Deck it. 🙌

**Comment by discolemonade01** [comment]
Thank you!
