### ISSUE TITLE
Option to control groups and not just individual lights? 

### ISSUE THREAD

**Issue by DrPurrple** [GeekyEggo/GoveeController#56]
Hey there, I was wondering if it's possible to even control groups of lights and not just individual fixtures? Would make things a bit more convenient. :)

**Comment by GeekyEggo** [comment]
Hey @DrPurrple 👋 There’s no option to control groups at the moment, however it is possible to control multiple lights using a “Multi-action” in Stream Deck, and then adding a Govee action for each light you wish to control. Let me know if this solves what you’re trying to achieve.🤞

**Comment by DrPurrple** [comment]
Thank you for your reply. And you're absolutely right. I am still new in the Stream Deck world and that isn't something I considered. I feel silly now 😅 

I can confirm the Multi Action command works. The reaction time could be a bit better but it works pretty good already so no complaints. If you spam on/off too much, it kind of stops responding and you have to try again in a while, but that is not a problem during normal conditions since no one uses the lights like that.

Thanks again!

**Comment by GeekyEggo** [comment]
Happy to hear this achieves what you were looking for 🙌

RE the spamming on/off button; the Govee API has throttling to reduce the number of calls in a set time (IIRC, it's 10 per device, per minute).
