### ISSUE TITLE
Feature Idea: Tap-to-Run from Stream Deck

### ISSUE THREAD

**Issue by calebsg0** [GeekyEggo/GoveeController#59]
I have the Govee H601A 6" down lights, which are amazing! Right now in Stream Deck I have to set the color and brightness light by light. If there was a way to initiate a Tap-to-Run scene via the Stream Deck that would make it super easy to have multiple lighting scenarios available via Stream Deck. Would this be something that could be considered for future development?

**Comment by GeekyEggo** [comment]
Hey @calebsg0 👋 scenes is something I’d really like to add to the plugin, but sadly Govee  doesn’t yet have a public API that enables this. In the mean time, you should be able to achieve the desired effect using a combination of this plugin’s actions within a Stream Deck “multi-action”. Hope this helps!
