### ISSUE TITLE
Govee Actions not Working

### ISSUE THREAD

**Issue by Jason-society** [GeekyEggo/GoveeController#61]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

Smart light bulbs and a floor lamp.

### Bug Description

None of the actions I try to use on streamdeck are working. API is there. Streamdeck reads and sees the lights but when pushing a button to generate an action on the stream deck the lights do nothing.

### Logs

```bash
The logs requested have too many characters for this box.
```

**Comment by Jason-society** [comment]
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/13221596/GoveeController.log)

**Comment by tylertejas** [comment]
im having the same issue

**Comment by ardziej** [comment]
Your device is offline.
What you can do to confirm it:
`curl --location 'https://developer-api.govee.com/v1/devices' \
--header 'Govee-API-Key: <API KEY>'`

You will receive a list of your devices. Get values from data->devices->device & model

Then you can get more details:

`curl --location 'https://developer-api.govee.com/v1/devices/state?device=<DEVICE>&model=<MODEL>' \
--header 'Govee-API-Key: <API KEY>'`
In response: data.properties.online = false

Removing the device and adding it one more time with the WiFi setup solved the issue.(Govee App)

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
