### ISSUE TITLE
its not working for my strip lights

### ISSUE THREAD

**Issue by nrmemeo** [GeekyEggo/GoveeController#62]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

H613E

### Bug Description

its not supported by the app i checked it would be cool beans if you decided to add this device so i could control my lights with my stream deck thanks

### Logs

```bash
please
```

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
