### ISSUE TITLE
Doesn't control Groups within Govee

### ISSUE THREAD

**Issue by scottayres** [GeekyEggo/GoveeController#67]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

macOS

### Govee Device

Various devices

### Bug Description

Within the Govee app we can group items and with 1 tap turn them off or on, as well as set the color. Can we do this with this Elgato plugin?

**Comment by GeekyEggo** [comment]
Hi @scottayres, apologies for the delayed response — Govee's API doesn't currently support controlling groups, however you should be able to achieve similar behaviour using Multi-Actions within Stream Deck.
