### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by AkalaGit** [GeekyEggo/GoveeController#68]
Lacks a lot of features but could be great.

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
