### ISSUE TITLE
API Key not taking

### ISSUE THREAD

**Issue by misterburnz** [GeekyEggo/GoveeController#7]
I snagged your plugin (which FINALLY someone was able to make one for Govee, big thanks) but when I put the API key in, it just holds at "Connecting..." indefinitely and if I click away from that module, I have to re-enter my API, going into a bit of a loop. Any suggestions?

**Comment by GeekyEggo** [comment]
Hey @misterburnz, could I ask you to try with the latest beta version ([download link](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin)); if the problem persists we can take a further look into things.

**Comment by misterburnz** [comment]
I've deleted the old folder, then ran the beta with the link you provided, and it still appears to be having the same issue

**Comment by GeekyEggo** [comment]
No problems; if upload the log files here, I'll take a look at what's happening. They can be found at:
`%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`

**Comment by misterburnz** [comment]
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/8181028/GoveeController.log)

I assume that is the file you're looking for?

**Comment by GeekyEggo** [comment]
The logs aren't highlighting any issues; would you be able to screen capture what's happening? You should be able to upload the .mp4 directly here.

**Comment by misterburnz** [comment]
API field covered, however it is the most recent one I've received from Govee. 

https://user-images.githubusercontent.com/88789518/157251998-2436a8c6-c11c-4759-800f-8a916d6e7877.mp4

**Comment by GeekyEggo** [comment]
@misterburnz apologies for my lack of reply; did this issue ever resolve itself?

**Comment by GeekyEggo** [comment]
Hey @misterburnz, as part of #20, I've reworked how HTTP requests are made. This also includes changes to the settings window. Here's a link to the [latest beta, v1.2.2](https://github.com/GeekyEggo/GoveeController/raw/fix-http/dist/com.geekyeggo.goveecontroller.streamDeckPlugin), hopefully this might help 🤞
