### ISSUE TITLE
Support for Govee Device H608A

### ISSUE THREAD

**Issue by akelshareif** [GeekyEggo/GoveeController#70]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

Govee RBIC String Downlights H608A

### Bug Description

The current app version does not support Govee device H608A. I'd appreciate it if it can be added, or alternatively, I can make a PR to add that device support if I was given some information on how to add it. 

The device is currently listed as supported by the govee api.

**Comment by skyline4044** [comment]
Hi i have same problem please fix thank you 👍

**Comment by PeterBursky** [comment]
Hi, i'm in a similar situation - have the H608B device, which is listed on the API supported devices list, but it won't show on the list of the devices in the plug-in. Happy to provide any additional information if required. Thanx!

**Comment by skyline4044** [comment]
Fixed we have to use Alfa https://github.com/GeekyEggo/GoveeController/issues/63#issuecomment-1931692412

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
