### ISSUE TITLE
Unable to enter API key during setup

### ISSUE THREAD

**Issue by FindHarambe** [GeekyEggo/GoveeController#71]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

N/A

### Bug Description

![image](https://github.com/GeekyEggo/GoveeController/assets/168695679/f033c286-2c7b-4fd5-b099-f2f568f987e3)
No box to enter API (Version 2.0.0.2)

**Comment by LockeAG** [comment]
I think you have to reinstall, but either way, the app stopped working for several devices.

**Comment by GeekyEggo** [comment]
Hi @FindHarambe, v1.3 is now available on Marketplace; could I ask you to try with this version and let me know if you have any luck please.

**Comment by kingerni** [comment]
> Hi @FindHarambe, v1.3 is now available on Marketplace; could I ask you to try with this version and let me know if you have any luck please.

had the same issue and reinstalled the new version from the elgato marktplace and everthying works fine so far.
