### ISSUE TITLE
Govee + Streamdeck

### ISSUE THREAD

**Issue by JungleChili** [GeekyEggo/GoveeController#78]
![{02265BA0-84C5-4C56-9BD7-08F3CAE23126}](https://github.com/user-attachments/assets/74a3f74c-a490-4d34-b26d-fa0b07edaeeb)

Service is busy please try again later.
Tried the following:
New api
Remove clean any trace of the plugin in dir and reg then reinstall.
Different User Profile.
Disabled firewalls.

Govee app on phone controls them just fine, but the streamdeck just errors.

**Comment by klutzo** [comment]
I get the same prompt 'Service is busy please try again later'

**Comment by GeekyEggo** [comment]
Sadly this is an error on Govee's side, and looks to be affecting all integrations using their public API.

I suspect they'll implement a fix soon, but I would encourage getting in touch with them if not fixed within 2-3 days to let them know.
