### ISSUE TITLE
"Service is busy. Please Try Again Later"

### ISSUE THREAD

**Issue by icantpronouncethis** [GeekyEggo/GoveeController#79]
It was working perfectly fine in the morning of Sept 16th. 

"Service is busy. Please Try Again Later"
This message popped up in the afternoon.
Tried waiting it out for the rest of the day with the same result.
Checked in the morning of Sep 17, same result.
Reapplied a new API Key from Govee and inputted in to the controller, same result.

What should I do?

**Comment by GeekyEggo** [comment]
Please see #78.
