### ISSUE TITLE
API Key issue.

### ISSUE THREAD

**Issue by Uzae** [GeekyEggo/GoveeController#8]
![image](https://user-images.githubusercontent.com/34613124/159175028-64b1ba0e-ac1e-4d55-b1c3-94f5965ce848.png)
I paste the api key and then it shows "Setup failed: success" and the button does nothing. I've tried getting a new API key or removing the dashes but it seems the format originally was correct but it's just not working.

**Comment by GeekyEggo** [comment]
Hey @Uzae, could I ask you to download and install the latest beta version ([direct link](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin)), and try again. Hopefully this should fix the problem.

**Comment by Uzae** [comment]
> Hey @Uzae, could I ask you to download and install the latest beta version ([direct link](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin)), and try again. Hopefully this should fix the problem.

So it has worked, however my device isn't showing up. They're the Govee RGBIC LED Strip Lights. 
![image](https://user-images.githubusercontent.com/34613124/159192038-8a299e98-cb67-47a1-9767-cce4a4ecca96.png)

**Comment by GeekyEggo** [comment]
Glad to hear that solved the problem; regarding the lights not being listed:
1. Is the device listed [here](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf)?
1. Are the lights connected via WiFi? (Bluetooth is not supported by the Govee AIP)

**Comment by GeekyEggo** [comment]
Closing as inactive, but I am happy to discuss further if required.
