### ISSUE TITLE
Govee API changed | PlugIn Outdated

### ISSUE THREAD

**Issue by GulliDulli** [GeekyEggo/GoveeController#82]
Hi everyone,

I have just downloaded your plug-in and noticed that my “H600D” Govee spots are not recognized.

There are new products to buy from Govee that are not supported by your plugin. This is a bit of a bummer, which is why I would like to make this appeal.

The Govee API has been updated with more features and I would like to ask you if you plan to update your Govee PlugIn accordingly and include all features. 

Here is the documentation: https://developer.govee.com/reference/get-you-devices

I'm sure everyone here would be very grateful!

Best Regards
GulliDulli

**Comment by GeekyEggo** [comment]
Thanks for all your patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
