### ISSUE TITLE
BUttons not working

### ISSUE THREAD

**Issue by cowkillla** [GeekyEggo/GoveeController#83]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govee's API](https://developer.govee.com/docs/support-product-model).

### Operating System

Windows

### Govee Device

h70b1
h6056

### Bug Description

API is connected but lights not responding to streamdeck control. They are functioning fine via govee app

**Comment by cowkillla** [comment]
They worked prior to the latest govee app update and new plugin

**Comment by GeekyEggo** [comment]
Hi @cowkillla, to investigate this, I’ll need the logs — are you on Windows or macOS?

**Comment by cowkillla** [comment]
It was an issue Govee side not the app. Seems they weren't connected to the wifi after the last bout of storms made the power blip several times. all good now!
