### ISSUE TITLE
Failure to install to stream deck

### ISSUE THREAD

**Issue by TonyS45** [GeekyEggo/GoveeController#87]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govee's API](https://developer.govee.com/docs/support-product-model).

### Operating System

Windows

### Govee Device

H600D

### Bug Description

When trying to install off of the elgato store the program replies  unable to install "govee controlller" pluggin

**Comment by TonyS45** [comment]
forgot to mention on the latest version of the steamdeck updates

**Comment by GeekyEggo** [comment]
Hey Tony, could you try [downloading the plugin directly](https://github.com/GeekyEggo/GoveeController/raw/refs/heads/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) from this repository to see if that works please.

**Comment by TonyS45** [comment]
Thank you for the response I ended up restarting my computer and it went
perfect
