### ISSUE TITLE
No devices showing in Govee Controller for Streamdeck

### ISSUE THREAD

**Issue by jaelynmackenzie** [GeekyEggo/GoveeController#9]
I originally had the setup failed:success poppup when attempting to enter API but after reading the previous forums I downloaded the updated version that was linked in those comments. API is now accepted. But the the problem I am now experiencing is in the device list none of my devices are showing. I have the h6125 (product model) strip lights. I saw that a previous poster had been having this same problem but i did not see a solution for it.

**Comment by GeekyEggo** [comment]
Hi @jaelynmackenzie, thank you for your efforts into resolving the problem; everything you've tried would've been my recommendations. I've reviewed the list of supported devices within the [Govee API document](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf), and sadly H6125 isn't listed there I'm sorry to say but I won't be able to resolve this issue.

Hopefully Govee add support for this device soon! 🤞

**Comment by MozohTTV** [comment]
i have the same problem i have the Govee RGBIC LED Strip

**Comment by GeekyEggo** [comment]
@MozohTTV are you seeing “failed: success”? If so, that is resolved in the latest beta.

**Comment by MozohTTV** [comment]
no i dont that one is solved but i can't see any device in the device list

**Comment by GeekyEggo** [comment]
Could I ask you to upload your logs files please; they’re found at:
`%appdata%\Elgato\StreamDeck\Plugins\com.geekyeggo.goveecontroller.sdPlugin\logs`

**Comment by MozohTTV** [comment]
my device is the h6127 btw

**Comment by MozohTTV** [comment]
here you go
[GoveeController.log](https://github.com/GeekyEggo/GoveeController/files/9035208/GoveeController.log)

**Comment by GeekyEggo** [comment]
> my device is the h6127 btw

Sadly this model doesn’t look to be supported by [Govee’s API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf).
